In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import pickle

In [ ]:
## load trained model, scaler, onehot encoder, label encoder
model = load_model('/content/drive/MyDrive/ANN CLASSIFICATION/model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
## Load encoder and scaler
with open('/content/drive/MyDrive/ANN CLASSIFICATION/label_encoder_gender.pkl','rb') as file:
  label_encoder_gender = pickle.load(file)

with open('/content/drive/MyDrive/ANN CLASSIFICATION/onehot_encoder_geo.pkl','rb') as file:
  onehot_encoder_geo = pickle.load(file)

with open('/content/drive/MyDrive/ANN CLASSIFICATION/scaler.pkl','rb') as file:
  scaler = pickle.load(file)

In [ ]:
## Input Data
input_data = {
    'CreditScore': 600,
    'Geography': "France",
    'Gender': "Male",
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [ ]:
# Convert input data into dataframe

input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [ ]:
## OneHot Encode 'Geography
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(),columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
## Combine OneHot Encoded value with input_data
input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [ ]:
## label encode categorical variables (gender)
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [ ]:
## Scaling the input_data
scaled_input = scaler.transform(input_df)

In [ ]:
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [ ]:
## Prediction
prediction = model.predict(scaled_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step

array([[0.04741747]], dtype=float32)

In [ ]:
prediction_proab = prediction[0][0]
prediction_proab

np.float32(0.04741747)

In [ ]:
if prediction_proab > 0.5:
  print("The customer is likely to churn.")
else:
  print("The customer is not likely to churn.")

The customer is not likely to churn.